---
title: "Homework 4"
author: "PSTAT 115, Fall 2023"
date: "__Due on Nov 30th ***, 2023 at 11:59 pm__"
output:
  pdf_document: default
  html_document:
    df_print: paged
urlcolor: blue
editor_options:
  markdown:
    wrap: 72
---


```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=TRUE, 
                      cache=FALSE, 
                      fig.width=5, 
                      fig.height=5,
                      fig.align='center')
r = function(x, digits=2){ round(x, digits=digits) }
indent1 = '    '      
indent2 = paste(rep(indent1, 2), collapse='')
library(tidyverse)
library(reshape2)
library(magrittr)
library(testthat)
library(rstan)
```



### Problem 1. Frequentist Coverage of The Bayesian Posterior Interval.

Suppose that $y_1,..,y_n$ is an IID sample from a
$Normal(\mu, 1)$. We wish to estimate $\mu$.

**1a.** For Bayesian inference, we will assume the prior distribution
$\mu \sim Normal(0,\frac{1}{\kappa_0})$ for all parts below. Remember,
from lecture that we can interpret $\kappa_0$ as the pseudo-number of
prior observations with sample mean $\mu_0 = 0$. State the posterior
distribution of $\mu$ given $y_1,..,y_n$. Report the lower and upper
bounds of the $95\%$ quantile-based posterior credible interval for
$\mu$, using the fact that for a normal distribution with standard
eviation $\sigma$, approximately $95\%$ of the mass is between
$\pm 1.96\sigma$. \newline

    
**1b**. Plot the length of the posterior credible interval as a function
of $\kappa_0$, for $\kappa_0 = 1, 2, ..., 25$ assuming $n=10$. Report
how this prior parameter effects the length of the posterior interval
and why this makes intuitive sense.

    


**1c**. Now we will evaluate the *frequentist coverage* of the posterior
credible interval on simulated data. Generate 1000 data sets where the
true value of $\mu=0$ and $n=10$. For each dataset, compute the
posterior $95\%$ interval endpoints (from the previous part) and see if
it the interval covers the true value of $\mu = 0$. Compute the
frequentist coverage as the fraction of these 1000 posterior 95%
credible intervals that contain $\mu=0$. Do this for each value of
$\kappa_0 = 1, 2, ..., 25$. Plot the coverage as a function of
$\kappa_0$.

   

**1d.** Repeat the 1c but now generate data assuming the true $\mu=1$.

    
**1e**. Explain the differences between the coverage plots when the true
$\mu$ = 0 and the true $\mu = 1$. For what values of $\kappa_0$ do you
see closer to nominal coverage (i.e. 95%)? For what values does your
posterior interval tend to overcover (the interval covers the true value
more than 95% of the time)? Undercover (the interval covers the true
value less than 95% of the time)? Why does this make sense?

### Problem 2. Rstan Warm up for Women's World Cup

Chinese Women soccer team has won AFC Woman's Asian Cup recently. Suppose you are interested in the following World Cup performance of Chinese women soccer team. Let $\lambda$ be the be the average number of goals scored of Chinese Women team. We will analyze $\lambda$ by Gamma-Poisson model where data $Y_i$ is the observed number of goals scored in World Cup games. ie. we have $Y_i|\lambda \sim Pois(\lambda)$ and $\lambda \sim Gamma(a, b)$. According to a sport analyst, they believe that $\lambda$ follows a Gamma distribution with $a = 1$ and $b = 0.25$. 

**2a.** 
Compute the theoretical posterior parameters a, b, and also posterior mean mu.

    
**2b.** 
Create a stan file named `women_cup.stan`, use Rstan to Report and
estimate of the posterior mean of the scoring rate by computing the sample
average of all Monte Carlo samples of $\lambda$.
**2c.**
Produce histogram for simulated lambda and density plot for theoretical posterior distribution of lambda. Does the simulated results coincide with the theoretical ones? Briefly explain your answer.   

    
**2d.**
Right now, we have lambda samples generated by Rstan. Use them as samples from posterior distribution to compute the mean of predicative posterior distribution to estimate the possible goal scored for next game for Chinese women soccer team.

   
### Problem 3. Bayesian inference for the normal distribution in Stan.

Create a new Stan file by selecting "Stan file" in the Rstudio menu.
Save it as `IQ_model.stan`. We will make some basic modifications to the
template example in the default Stan file for this problem. Consider the
IQ example used from class. Scoring on IQ tests is designed to yield a
N(100, 15) distribution for the general population. We observe IQ scores
for a sample of $n$ individuals from a particular town,
$y_1, \ldots y_n \sim N(\mu, \sigma^2)$. Our goal is to estimate the
population mean in the town. Assume the
$p(\mu, \sigma) = p(\mu \mid \sigma)p(\sigma)$, where
$p(\mu \mid \sigma)$ is $N(\mu_0, \sigma/\sqrt{\kappa_0})$ and
$p(\sigma)$ is Gamma(a, b). Before you administer the IQ test you
believe the town is no different than the rest of the population, so you
assume a prior mean for $\mu$ of $\mu_0 = 100$, but you aren't sure
about this a priori and so you set $\kappa_0 = 1$ (the effective number
of pseudo-observations). Similarly, a priori you assume $\sigma$ has a
mean of 15 (to match the intended standard deviation of the IQ test) and
so you decide on setting $a=15$ and $b=1$ (remember, the mean of a Gamma
is a/b). Assume the following IQ scores are observed:


**3a**. Make a scatter plot of the posterior distribution of the median,
$\mu$, and the precision, $1/\sigma^2$. Put $\mu$ on the x-axis and
$1/\sigma^2$ on the y-axis. What is the posterior relationship between
$\mu$ and $1/\sigma^2$? Why does this make sense? *Hint:* review the
lecture notes.

   
**3b**. You are interested in whether the mean IQ in the town is greater
than the mean IQ in the overall population. Use Stan to find the
posterior probability that $\mu$ is greater than 100.

    
**3c.** You notice that two of the seven scores are significantly lower
than the other five. You think that the normal distribution may not be
the most appropriate model, in particular because you believe some
people in this town are likely have extreme low and extreme high scores.
One solution to this is to use a model that is more robust to these
kinds of outliers. The [Student's t
distribution](https://en.wikipedia.org/wiki/Student%27s_t-distribution)
and the [Laplace
distribution](https://en.wikipedia.org/wiki/Laplace_distribution) are
two so called "heavy-tailed distribution" which have higher
probabilities of outliers (i.e. observations further from the mean).
Heavy-tailed distributions are useful in modeling because they are more
robust to outliers. Fit the model assuming now that the IQ scores in the
town have a Laplace distribution, that is
$y_1, \ldots, y_n \sim Laplace(\mu, \sigma)$. Create a copy of the
previous stan file, and name it "IQ_laplace_model.stan". *Hint:* In the
Stan file you can replace `normal` with `double_exponential` in the
model section, another name for the Laplce distribution. Like the normal
distribution it has two arguments, $\mu$ and $\sigma$. Keep the same
prior distribution, $p(\mu, \sigma)$ as used in the normal model. Under
the Laplace model, what is the posterior probability that the median IQ
in the town is greater than 100? How does this compare to the
probability under the normal model? Why does this make sense?

    